# -*- coding: utf-8 -*-
__title__ = "Select \ncorrupted groups"                           # Name of the button displayed in Revit UI
__doc__ = """Version = 1.0
Date    = 21.11.2023
_____________________________________________________________________
Description:
This script selects groups with excluded elements
_____________________________________________________________________
How-to:
-> Click on the button

_____________________________________________________________________

To-Do:
- 
_____________________________________________________________________
Author: Jakub Dvořáček"""                                           # Button Description shown in Revit UI

# EXTRA: You can remove them.
__author__ = "Jakub Dvořáček"                                   # Script's Author
__helpurl__ = "https://atelier99cz.sharepoint.com/sites/Atelier99/SitePages/Main%20pages/BIM_Revit.aspx"     # Link that can be opened with F1 when hovered over the tool in Revit UI.


# ╦╔╦╗╔═╗╔═╗╦═╗╔╦╗╔═╗
# ║║║║╠═╝║ ║╠╦╝ ║ ╚═╗
# ╩╩ ╩╩  ╚═╝╩╚═ ╩ ╚═╝ IMPORTS
# ==================================================
import clr
clr.AddReference('RevitAPI')
clr.AddReference('RevitAPIUI')
from Autodesk.Revit.DB import *
from rpw import db, ui
from System.Collections.Generic import List

# ╦  ╦╔═╗╦═╗╦╔═╗╔╗ ╦  ╔═╗╔═╗
# ╚╗╔╝╠═╣╠╦╝║╠═╣╠╩╗║  ║╣ ╚═╗
#  ╚╝ ╩ ╩╩╚═╩╩ ╩╚═╝╩═╝╚═╝╚═╝ VARIABLES
# ==================================================
doc   = __revit__.ActiveUIDocument.Document   # Document   class from RevitAPI that represents project. Used to Create, Delete, Modify and Query elements from the project.
uidoc = __revit__.ActiveUIDocument          # UIDocument class from RevitAPI that represents Revit project opened in the Revit UI.
app   = __revit__.Application                 # Represents the Autodesk Revit Application, providing access to documents, options and other application wide data and settings.

# ╔═╗╦ ╦╔╗╔╔═╗╔╦╗╦╔═╗╔╗╔╔═╗
# ╠╣ ║ ║║║║║   ║ ║║ ║║║║╚═╗
# ╚  ╚═╝╝╚╝╚═╝ ╩ ╩╚═╝╝╚╝╚═╝ FUNCTIONS
# ==================================================
# Method to isolate elements in a view

# ╔╦╗╔═╗╦╔╗╔
# ║║║╠═╣║║║║
# ╩ ╩╩ ╩╩╝╚╝ MAIN
# ==================================================



t = Transaction(doc,__title__)

t.Start()  # <- Transaction Start

groups = FilteredElementCollector(doc, doc.ActiveView.Id).OfClass(Group).WhereElementIsNotElementType().ToElements()
cor_groups_ids = []
str1 = "vyloučené prvky"
for group in groups:
    if str1 in group.Name:
        cor_groups_ids.append(group)
msg = "There are " + str(len(cor_groups_ids)) + " corrupted groups in the model"
ui.forms.Alert(msg, title="Corrupted groups")

selection = ui.Selection(cor_groups_ids)

t.Commit()  # <- Transaction End

